### ISSUE TITLE
Configuration issue which breaks Keepalived v1.3.5

### ISSUE THREAD

**Issue by elcomtik** [uZer/ansible-role-keepalived#6]
Hi, I discovered bad syntax in template, which prevents Keepalived v1.3.5 from strating a working.  In your template notification_email section is missing closing parenthesis, which causes daemon to not fully load all lines. Quick fix is to add parenthesis and problem is solved. 

Anyway big thanks for your work, this role is exatcly what i needs.

**Comment by uZer** [comment]
Hey elcomtik! Thanks for your report.
Feel free to fork and/or PR something here, I guess this is a great oportunity for hacktoberfest 2018 ;)

**Comment by uZer** [comment]
Should be fixed now, thanks!
